# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sakuya.plugins.acnh.proto.meteonook_pb2 as meteonook__pb2


class MeteoNookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOverview = channel.unary_unary(
                '/MeteoNook/GetOverview',
                request_serializer=meteonook__pb2.IslandInfo.SerializeToString,
                response_deserializer=meteonook__pb2.Overview.FromString,
                )


class MeteoNookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeteoNookServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverview,
                    request_deserializer=meteonook__pb2.IslandInfo.FromString,
                    response_serializer=meteonook__pb2.Overview.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MeteoNook', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MeteoNook(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MeteoNook/GetOverview',
            meteonook__pb2.IslandInfo.SerializeToString,
            meteonook__pb2.Overview.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
