# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meteonook.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meteonook.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmeteonook.proto\";\n\nIslandInfo\x12\x0c\n\x04seed\x18\x01 \x01(\r\x12\x1f\n\nhemisphere\x18\x02 \x01(\x0e\x32\x0b.Hemisphere\"-\n\x08Overview\x12\x10\n\x08\x66orecast\x18\x01 \x01(\t\x12\x0f\n\x07pattern\x18\x02 \x01(\t*\"\n\nHemisphere\x12\t\n\x05NORTH\x10\x00\x12\t\n\x05SOUTH\x10\x01\x32\x34\n\tMeteoNook\x12\'\n\x0bGetOverview\x12\x0b.IslandInfo\x1a\t.Overview\"\x00\x62\x06proto3'
)

_HEMISPHERE = _descriptor.EnumDescriptor(
  name='Hemisphere',
  full_name='Hemisphere',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORTH', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOUTH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=127,
  serialized_end=161,
)
_sym_db.RegisterEnumDescriptor(_HEMISPHERE)

Hemisphere = enum_type_wrapper.EnumTypeWrapper(_HEMISPHERE)
NORTH = 0
SOUTH = 1



_ISLANDINFO = _descriptor.Descriptor(
  name='IslandInfo',
  full_name='IslandInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='IslandInfo.seed', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hemisphere', full_name='IslandInfo.hemisphere', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=78,
)


_OVERVIEW = _descriptor.Descriptor(
  name='Overview',
  full_name='Overview',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='forecast', full_name='Overview.forecast', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pattern', full_name='Overview.pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=125,
)

_ISLANDINFO.fields_by_name['hemisphere'].enum_type = _HEMISPHERE
DESCRIPTOR.message_types_by_name['IslandInfo'] = _ISLANDINFO
DESCRIPTOR.message_types_by_name['Overview'] = _OVERVIEW
DESCRIPTOR.enum_types_by_name['Hemisphere'] = _HEMISPHERE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IslandInfo = _reflection.GeneratedProtocolMessageType('IslandInfo', (_message.Message,), {
  'DESCRIPTOR' : _ISLANDINFO,
  '__module__' : 'meteonook_pb2'
  # @@protoc_insertion_point(class_scope:IslandInfo)
  })
_sym_db.RegisterMessage(IslandInfo)

Overview = _reflection.GeneratedProtocolMessageType('Overview', (_message.Message,), {
  'DESCRIPTOR' : _OVERVIEW,
  '__module__' : 'meteonook_pb2'
  # @@protoc_insertion_point(class_scope:Overview)
  })
_sym_db.RegisterMessage(Overview)



_METEONOOK = _descriptor.ServiceDescriptor(
  name='MeteoNook',
  full_name='MeteoNook',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=163,
  serialized_end=215,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOverview',
    full_name='MeteoNook.GetOverview',
    index=0,
    containing_service=None,
    input_type=_ISLANDINFO,
    output_type=_OVERVIEW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METEONOOK)

DESCRIPTOR.services_by_name['MeteoNook'] = _METEONOOK

# @@protoc_insertion_point(module_scope)
